// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parallelMovementRcpp_portion
NumericMatrix parallelMovementRcpp_portion(const NumericMatrix& apop, const IntegerMatrix& apopmat, const IntegerMatrix& apoplocs, const NumericMatrix acent, const NumericMatrix road, const int pref, const int cent_col, const double inc);
RcppExport SEXP _crossR_parallelMovementRcpp_portion(SEXP apopSEXP, SEXP apopmatSEXP, SEXP apoplocsSEXP, SEXP acentSEXP, SEXP roadSEXP, SEXP prefSEXP, SEXP cent_colSEXP, SEXP incSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type apop(apopSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type apopmat(apopmatSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type apoplocs(apoplocsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type acent(acentSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type road(roadSEXP);
    Rcpp::traits::input_parameter< const int >::type pref(prefSEXP);
    Rcpp::traits::input_parameter< const int >::type cent_col(cent_colSEXP);
    Rcpp::traits::input_parameter< const double >::type inc(incSEXP);
    rcpp_result_gen = Rcpp::wrap(parallelMovementRcpp_portion(apop, apopmat, apoplocs, acent, road, pref, cent_col, inc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crossR_parallelMovementRcpp_portion", (DL_FUNC) &_crossR_parallelMovementRcpp_portion, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_crossR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
