# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelMovementRcpp_portion <- function(apop, apopmat, apoplocs, acent, road, pref, cent_col, inc) {
    .Call(`_crossR_parallelMovementRcpp_portion`, apop, apopmat, apoplocs, acent, road, pref, cent_col, inc)
}

