# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelMovementRcpp_portion <- function(apop, apopmat, apoplocs, acent, pref) {
    .Call(`_crossR_parallelMovementRcpp_portion`, apop, apopmat, apoplocs, acent, pref)
}

MovementRcppParallel <- function(apop, apopmat, apoplocs, acent, pref) {
    .Call(`_crossR_MovementRcppParallel`, apop, apopmat, apoplocs, acent, pref)
}

parallelMovementRcpp_portion <- function(apop, apopmat, apoplocs, acent, road, pref, cent_col, inc) {
    .Call(`_crossR_parallelMovementRcpp_portion`, apop, apopmat, apoplocs, acent, road, pref, cent_col, inc)
}

MovementRcppParallel <- function(apop, apopmat, apoplocs, acent, road, pref, cent_col, inc) {
    .Call(`_crossR_MovementRcppParallel`, apop, apopmat, apoplocs, acent, road, pref, cent_col, inc)
}

rcpp_hello_world <- function() {
    .Call(`_crossR_rcpp_hello_world`)
}

